<?php
/**
 * Copyright (c) 2018 MageWorkshop. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \MageWorkshop\AdminResponse\Block\AdminResponse $block */ ?>
<?php if ($adminResponse = $block->getAdminResponse()) : ?>
    <?php $adminResponseTooltipText = $block->getAdminResponseTooltipText(); ?>
    <article class="review-item-admin-response">
        <p class="review-item-admin-response-title">
            <strong<?php if ($adminResponseTooltipText): ?> class="tooltip-toggle"<?php endif; ?>>
                <?= $block->escapeHtml($block->getAdminResponseTitle()); ?>
            </strong>
            <?php if ($adminResponseTooltipText): ?>
                <span class="tooltip-content"><?= $block->escapeHtml($adminResponseTooltipText); ?></span>
            <?php endif; ?>
        </p>
        <p><?= $block->escapeHtml($adminResponse); ?></p>
    </article>
<?php endif; ?>