<?php

/**

* Copyright © Magento, Inc. All rights reserved.

* See COPYING.txt for license details.

*/



// @codingStandardsIgnoreFile



/* @var \Magento\Wishlist\Block\Share\Email\Items $block */

?>

<?php $l = $block->getWishlistItemsCount();


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cart = $objectManager->get('\Magento\Checkout\Model\Cart');  
$subTotal = number_format($cart->getQuote()->getSubtotal(),0);
$grandTotal = number_format($cart->getQuote()->getGrandTotal(),0);
$shipping_charge = "";
 if($subTotal <= 1000){
	$shipping_charge ='₦4,500';
 }else if($subTotal > 1000 && $subTotal < 50000){
	$shipping_charge ='₦4,500';
 }else{
	$shipping_charge ='FREE';
 }
 ?>

<?php echo $l;?>

<div class="cart_btm_left_container">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('precise_cart_return_payment')->toHtml();?>
	<div class="clear_both"></div>
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('precise_trust_pilot_secure')->toHtml();?>
	<!-- 14 return policy -->

	<!--  <div class="cart_btm_left return_policy">

	<h4 class="cart_btm_title">7 Days Returns</h4>

	<p>If you change your mind</p>

	<img src="<?php echo $this->getViewFileUrl('images/icon_percent.png'); ?>" class="img-responsive" alt="14 days returns" />

	<img src="<?php echo $this->getViewFileUrl('images/trust_pilot.png'); ?>" class="img-responsive" alt="trust pilot" />

	</div>-->

	<!-- 14 return policy -->

	<!-- secure payment -->

	<!-- <div class="cart_btm_left secure_payment">

	<h4 class="cart_btm_title">Secure Payments</h4>

	<p>Personal details are protected</p>

	<img src="<?php echo $this->getViewFileUrl('images/icon_payment.png'); ?>" class="img-responsive" alt="14 days returns" />

	<img src="<?php echo $this->getViewFileUrl('images/icon_secure.png'); ?>" class="img-responsive" alt="trust pilot" />

	</div>-->

</div>

<div class="clear_both"></div>
<input type="hidden" value="1" id="checkdivexits"/>
<script>
	require([
			'jquery',
			'domReady!'
		], function ($) {
			
			
			setInterval(function() {
				var exits = $('#checkdivexits').val();
					if(parseInt(exits) > 0)
					{
						if($('#cart-totals').length){
							
							$('.cart-summary').prepend('<p class="delivery_option">Delivery Option</p><dl class="items methods"> <dd class="item-options"><div class="field choice item"><input type="radio" checked class="radio" value="storepickup_storepickup" id="static_s_method_storepickup_storepickup" name="ko_unique"><label class="label"  for="s_method_storepickup_storepickup"> Home Delivery	</label></div></dd><dd class="item-options"><div class="field choice item"><input type="radio" class="radio"  value="tablerate_bestway" id="static_s_method_tablerate_bestway" name="ko_unique"><label class="label"  for="s_method_tablerate_bestway">Store Collection</label></div></dd></dl>');
							
							$('#cart-totals .table-wrapper table tbody tr:nth-child(1)').closest('tr').after('<tr class="totals sub"><th class="mark" scope="row">Delivery Charge</th><td class="amount"><span class="price" data-th="Subtotal"><?php echo $shipping_charge;?></span></td></tr>');
							
							$('#checkdivexits').val('0');
							
							$('#discount-coupon-form').after('<div id="addtional-cart-total-block" class="table-wrapper"><table class="data table1 totals"><tbody></tbody><tr class="grand totals"><th class="mark" scope="row"><strong data-bind="i18n: title">Order Total</strong></th><td class="amount" data-th="Order Total"><strong><span class="price" >₦<?php echo $grandTotal;?></span></strong></td></tr></table></div>');
							
							clearInterval();
							
						}
					}
					$('#storepickup_storepickup').attr('checked','checked');
				},3000);
				
				$('#coupon_code').focus(function() {
					$('#redeem_button').attr('style','border: 1px solid #124c62 !important;background: #124c62 !important;');
				});
				$('#coupon_code').focusout(function(){
					$('#redeem_button').attr('style','');
				});
		});
</script>

