<?php
/**
 * Copyright (c) 2018 MageWorkshop. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var \MageWorkshop\DetailedReview\Block\Review\Product\View\ListView $block */ ?>
<?php
    $_items     = $block->getReviewsCollection()->getItems();
    $attributes = $block->getReviewFormAttributes();
    $format     = $block->getDateFormat() ? $block->getDateFormat() : \IntlDateFormatter::LONG;
    /** @var MageWorkshop\Core\Helper\View $viewHelper */
    $viewHelper = $block->getViewHelper();
?>
<?php if (count($_items)):?>
<div class="block review-list" id="customer-reviews"
     data-mage-init='{"mageWorkshop_detailedReview_listReviews": {}}'
>
<!--    <div class="block-title">-->
<!--        <strong>--><?php ///* @escapeNotVerified */ echo __('Customer Reviews') ?><!--</strong>-->
<!--    </div>-->
    <hr>
    <div class="block-content">
        <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div>
        <ol class="items review-items">

        <?php foreach ($_items as $_review): /** @var \Magento\Review\Model\Review $_review */ ?>
            <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                <div class="review-details">
                    <p class="review-author">
                        <strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong>
                    </p>
                    <br>
                    <ul class="items">
                        <?php /** @var \MageWorkshop\DetailedReview\Model\Attribute $attribute */
                            foreach ($attributes as $attribute):
                        ?>
                            <?php if ($attribute->getIsUserDefined() &&
                                ($value = $block->getAttributeValue($attribute, $_review))
                                && $attribute->getAttributePlacement() === 1
                                && !in_array($attribute->getFrontendInput(), ['textarea', 'image'])
                            ): ?>
                                <li class="<?php /* @escapeNotVerified */ echo $this->getLabelClass($attribute); ?>">
                                    <label><?php /* @escapeNotVerified */ echo $attribute->getFrontendLabel(); ?>:&nbsp;</label>
                                    <span>
                                        <?php if (is_array($value)): // visual swatch ?>
                                            <?php if (isset($value['src'])): ?>
                                                <br>
                                                <img src="<?php /* @escapeNotVerified */ echo $value['src']; ?>"
                                                     alt="<?php /* @escapeNotVerified */ echo $value['label']; ?>"
                                                />
                                            <?php else: // select/boolean ?>
                                                <?php /* @escapeNotVerified */ echo $value['label']; ?>
                                            <?php endif; ?>
                                        <?php else: // multiselect or text attributes ?>
                                            <?php /* @escapeNotVerified */ echo $value; ?>
                                        <?php endif; ?>
                                    </span><br>
                                 </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div class="review-content" itemprop="description">
                    <div class="review-title-block">
                        <p class="review-title"><?php echo $block->escapeHtml($_review->getTitle()) ?></p>
                        <span><?php /* @escapeNotVerified */ echo __('By') ?></span>
                        <p class="review-author">
                            <strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong>
                        </p>
                        <p class="review-date">
                            <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Posted on') ?></span>
                            <span ><?php /* @escapeNotVerified */ echo __('on') ?></span>
                            <time class="review-details-value" itemprop="datePublished" datetime="<?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?>">
                                <?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?>
                                <?php /* @escapeNotVerified */ echo $block->formatTime($_review->getCreatedAt()) ?>
                            </time>
    <!--                        <time class="review-details-value" itemprop="datePublished" datetime="--><?php ///* @escapeNotVerified */ echo $_review->getCreatedAt() ?><!--">--><?php ///* @escapeNotVerified */ echo $_review->getCreatedAt() ?><!--</time>-->
                        </p>
                    </div>
                    <?php if ($_review->getCustomerId()): ?>
                        <div id="verified-buyer" title="<?= __('Verified buyer'); ?>"></div>
                    <?php endif; ?>
                    <hr>
                    <p><?php echo $block->addReadMore($_review->getDetail()) ?></p>
                    <div class="additional-review-attributes">
                        <ul class="items">
                            <?php foreach ($attributes as $attribute): ?>
                                <?php if ($attribute->getFrontendInput() === 'image'): continue ?>
                                <?php endif; ?>
                                <?php if ($attribute->getIsUserDefined() &&
                                    ($value = $block->getAttributeValue($attribute, $_review))
                                    && (!$attribute->getAttributePlacement() || $attribute->getFrontendInput() === 'textarea')
                                ): ?>
                                    <li class="table-items <?php /* @escapeNotVerified */ echo $this->getLabelClass($attribute); ?>">
                                        <label><?php /* @escapeNotVerified */ echo $attribute->getFrontendLabel(); ?>:&nbsp;</label>
                                        <div class="attribute-value">
                                            <?php if (is_array($value)): // visual swatch ?>
                                                <?php if (isset($value['src'])): ?>
                                                    <img src="<?php /* @escapeNotVerified */ echo $value['src']; ?>"
                                                         alt="<?php /* @escapeNotVerified */ echo $value['label']; ?>"
                                                    />
                                                <?php else: // select/boolean ?>
                                                    <?php /* @escapeNotVerified */ echo $value['label']; ?>
                                                <?php endif; ?>
                                            <?php else: // multiselect or text attributes ?>
                                                <?php /* @escapeNotVerified */ echo $value; ?>
                                            <?php endif; ?>
                                        </div>
                                    </li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <?php echo $viewHelper->getListTextChildrenHtml($block, 'reviews.list.item.after', [
                            'reviews_collection' => $block->getReviewsCollection(),
                            'review' => $_review,
                            'attributes' => $attributes
                    ]);
                    ?>
                </div>
                <div class="review-ratings">
                    <?php if (count($_review->getRatingVotes())): // leave the container so it takes the free space ?>
                        <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                            <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                <span class="label rating-label"><span><?php echo $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
                                <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                    <meta itemprop="worstRating" content = "1"/>
                                    <meta itemprop="bestRating" content = "100"/>
                                    <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                        <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
                                    </span>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
<?php endif; ?>
