<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()){
   ?><input type="hidden" id="customer_is_login_not"  value="1"/><?php
}
else
{
?><input type="hidden" id="customer_is_login_not" value="0"/><?php	
}
?>


<?php $helper = $this->helper('Magento\Search\Helper\Data'); ?>

<div class="search-form">
	<div class="form-search">
	<div class="custom_seeach" id="show_searchblock">
	<button type="submit" title="Search" class="search-close" onclick="showHideFormSearch()"></button>
	<input type="hidden" value="0" id="onetimetoclear"/>
		<form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
					
			<div class="search-input-area" id="search-part-1">		
					<input id="search"
					   data-mage-init='{"quickSearch":{
							"formSelector":"#search_mini_form",
							"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
							"destinationSelector":"#search_autocomplete"}
					   }'
					   type="text"
					   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
					   value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
					   class="input-text form-control"
					   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
					   placeholder="<?php echo __('Search Products') ?>"
					   role="combobox"
					   aria-expanded="true"
					   aria-haspopup="false"
					   aria-autocomplete="both"
					   autocomplete="off"/>
					
					<button type="submit" title="Search" class="action-search button" style="margin: 15px 0;"><i class="fa fa-search"></i></button>
					<span id="clear_recent_search1" class="clear_recent_search" style="display: none">Clear</span>
					<div id="amasty-xsearch-loader" class="amasty-xsearch-loader amasty-xsearch-hide"></div>
			 </div>		
			
			
			
			<div class="search-result-area" id="search-part-2">
				<div class="searchSuggest">
					<?php echo $block->getChildHtml() ?>
					<span id="clear_recent_search" class="cleardata" >Clear</span>
				</div>
				
				<div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
				
			</div>	
		</form>
		</div>
	</div>
	<div class="actions-search">
	<input type="text" name="search" onclick="showHideFormSearch()" class="searchline" placeholder="Search products" />
		<button type="submit" title="Search" onclick="showHideFormSearch()" class="action-search"><i class="fa fa-search"></i></button>
	</div>
</div>

<script type="text/javascript">
	function showHideFormSearch(){
		require([
		'jquery'
		], function(jQuery){
			(function($) {
				$("#clear_recent_search1").click();
				if($('.search-form').hasClass('not-full')){
					$('html').toggleClass('search-not-full');
				}
				
				$('html').toggleClass('search-open');
				$('body').toggleClass('hideserachscroll');
				setTimeout(focusSearchField, 500);
			})(jQuery);
		});
	}
	
	function focusSearchField(){
		require([
		'jquery'
		], function(jQuery){
			(function($) {
				$('#search_mini_form input#search').focus();
			})(jQuery);
		});
	}
	

</script>
	<script>// <![CDATA[
	require([
			'jquery',
			'domReady!'
		], function ($) {
			$('body').on('click', function(e) {
					if (e.target.id == 'show_searchblock' || $(e.target).parents('#show_searchblock').length) {
						
					} else {
						if ($('body').hasClass('hideserachscroll')) {
							$('.custom_seeach .search-close').click();
						}
					}
				});
				$('#clear_recent_search1').on('click', function(e) {
					$('div > [data-search-block-type="recent_searches"]').hide();
					var clearsearch = $('#onetimetoclear').val();
					if(parseInt(clearsearch) < 1)
					{
						$('#amasty-xsearch-preload').append('<div class="amsearch-item"><a href="#" class="item-name">No Recent Search </a></div>');
						$('#onetimetoclear').val('1');
					}
					$('#clear_recent_search1').hide();
										
				});
				
				$('#clear_recent_search').on('click', function(e) {
					$('div > [data-search-block-type="recent_searches"]').hide();
					var clearsearch = $('#onetimetoclear').val();
					if(parseInt(clearsearch) < 1)
					{
						$('#amasty-xsearch-preload').append('<div class="amsearch-item"><a href="#" class="item-name">No Recent Search </a></div>');
						$('#onetimetoclear').val('1');
					}
										
				});
			
			var checkcustomer = $('#customer_is_login_not').val();
		
			if(checkcustomer < 1)
			{
				$('#cdz-login-form-dropdown').append('<span class="border"></span><a href="/sales/order/history/">My Order</a> <span class="border"></span><a href="/faqs/" class="link help_faq" >Help/FAQs</a>');
			}
			
		$('#search').keyup(function()
			{
				var numberOfcharacter = this.value.length;
				console.log(numberOfcharacter);
				if(numberOfcharacter > 2)
				{
					$('#clear_recent_search1').show();
				}else{
					$('#clear_recent_search1').hide();
				}
			});
			
		});
	// ]]>
</script>