<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Yosto\OpcLinkedProduct\Block\LinkedProducts */
use Magento\Catalog\Model\Product\Link;
?>

<?php
switch ($type = $block->getType()) {
    case Link::LINK_TYPE_RELATED:
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = $block->getTitle();
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case Link::LINK_TYPE_UPSELL:
        if ($exist = count($block->getItems())) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = $block->getTitle();
            $items = $block->getItems();
            $canItemsAddToCart = $block->canItemsAddToCart();
            $shuffle = 0;
            $limit = 0;

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case Link::LINK_TYPE_CROSSSELL:
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = $block->getTitle();;
            $items = $block->getItems();
            $shuffle = 0;
            $limit = 0;

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = $block->canItemsAddToCart();;
        }
        break;

    case 'other':
        break;
}
?>

<?php if ($exist):?>
    <div id="yosto-checkout-linked-product" class="opc-sidebar" style="display: none">
    <?php

    /**
     * Layout type stand for slider or normal
     * 0 -> slider
     * #0 -> normal
     */
    $layoutType = 0;
    $customClass = "yosto_related_product";
    ?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
    <?php if ($type == 'related'): ?>
    <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
    <?php else: ?>
    <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
    <?php endif; ?>
    <?php else: ?>
    <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <div class="products wrapper <?php if ($layoutType != 0):?>grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?> <?php endif; ?> ">
            <section class="<?php if ($layoutType != 0):?> products list items product-items <?php endif;?> <?php echo  $customClass . " slider responsive" ?>">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                    <?php $available = ''; ?>
                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                        <?php if (!$_item->getRequiredOptions()): ?>
                            <?php $available = 'related-available'; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($type == 'related' || $type == 'upsell'): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item" style="display: none;">' : '</div><div class="item product product-item" style="display: none;">' ?>
                    <?php else: ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                    <?php endif; ?>
                    <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                        <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                            <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                    <?php echo $block->escapeHtml($_item->getName()) ?></a>
                            </strong>

                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                            <?php if ($templateType): ?>
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($showAddTo || $showCart): ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span>+</span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span>+</span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showAddTo): ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?php echo $addToBlock->setProduct($_item)->getChildHtml(); ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </section>
        </div>
    </div>

    </div>
    <script type="text/javascript">
        require(['jquery', 'yosto.opc.product.slider'], function($) {
                var detectOpcSummary = setInterval(function () {
                    if ($('.opc-summary-wrapper').length) {
                        var checkoutDivBox = $('#checkout');
                        var linkedProductContent = $('#yosto-checkout-linked-product').detach();
                        checkoutDivBox.append(linkedProductContent);
                        $('#yosto-checkout-linked-product').fadeIn();
                        <?php if ($layoutType == 0):?>
                            $('.<?php echo $customClass ?>').slick({
                            dots: false,
                            infinite: false,
                            speed: 300,
                            slidesToShow: 3,
                            slidesToScroll: 3,
                            autoplay:true,
                            responsive: [
                                {
                                    breakpoint: 1024,
                                    settings: {
                                        slidesToShow: 3,
                                        slidesToScroll: 3,
                                        infinite: true,
                                        dots: false
                                    }
                                },
                                {
                                    breakpoint: 768,
                                    settings: {
                                        slidesToShow: 3,
                                        slidesToScroll: 3,
                                        mobileFirst: true
                                    }
                                },
                                {
                                    breakpoint: 480,
                                    settings: {
                                        slidesToShow: 2,
                                        slidesToScroll: 2,
                                        mobileFirst: true
                                    }
                                }
                            ]
                        });
                        <?php endif; ?>
                        clearInterval(detectOpcSummary);
                    }
                }, 1000);

            }
        );
    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {"bindSubmit": true}
            }
        }
        </script>
    <?php endif; ?>
<?php endif;?>