<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<script type="text/javascript">
	require([
		'jquery'
		], function(jQuery){
			(function($) {
				jQuery('.gender-select-block li a').click(function(e) {
					jQuery('.gender-select-block li a').removeClass('active');
                    var gender_id = jQuery(this).attr('id');
					jQuery('select#gender').val(gender_id);
					jQuery(this).addClass('active');
                });
			})(jQuery);
		});

</script>

<div class="field gender<?php if ($block->isRequired()) echo ' required' ?>">
	<div class="gender-select-block">
    	<ul>
        	<li><a id="1" class="gender-man"><span class="icon"></span> <span>Male</span></a></li>
        	<li><a id="2" class="gender-woman"><span class="icon"></span> <span>Female</span></a></li>
        </ul>
    </div>
    <label class="label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId('gender')?>"><span><?php /* @escapeNotVerified */ echo __('Gender') ?></span></label>
    <div class="control">
        <select id="<?php /* @escapeNotVerified */ echo $block->getFieldId('gender')?>" name="<?php /* @escapeNotVerified */ echo $block->getFieldName('gender')?>" title="<?php /* @escapeNotVerified */ echo __('Gender') ?>"<?php if ($block->isRequired()):?> class="validate-select" data-validate="{required:true}"<?php endif; ?> <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?>>
            <?php $options = $block->getGenderOptions(); ?>
            <?php $value = $block->getGender();?>
            <?php foreach ($options as $option):?>
                <option value="<?php /* @escapeNotVerified */ echo $option->getValue() ?>"<?php if ($option->getValue() == $value) echo ' selected="selected"' ?>><?php /* @escapeNotVerified */ echo __($option->getLabel()) ?></option>
            <?php endforeach;?>
        </select>
    </div>
</div>
