<?php
/**
 * Copyright (c) 2018 MageWorkshop. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \MageWorkshop\DetailedReview\Block\Review\Form $block */
?>
<div id="mageworkshop" data-bind="scope: 'mageworkshop'">
<!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script>
    window.fieldsConfig = <?php /* @escapeNotVerified */ echo $block->getReviewFieldsConfigurationJson(); ?>;
</script>

<script type="text/x-magento-init">
    {
        "#mageworkshop": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
</script>
