<?php
/**
 * Copyright © 2017 x-mage2(Yosto). All rights reserved.
 * See README.md for details.
 */

?>
<div class="import-export-tax-rates">
    <div class="import-tax-rates">
        <form id="import-form" class="admin__fieldset" action="<?php /* @escapeNotVerified */ 
        echo $block->getUrl('yosto_storepickup/import/save') ?>" method="post" enctype="multipart/form-data">
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="fieldset admin__field">
                <label for="import_storelocations_file" class="admin__field-label"><span>
                	<?php /* @escapeNotVerified */ echo __('Import Store Locations') ?></span></label>
                <div class="admin__field-control">
                    <input type="file" id="import_storelocations_file" name="import_storelocations_file" 
                    class="input-file required-entry"/>
                    <input type="submit" value="submit" />
                </div>
            </div>
        </form>
    </div>
</div>
