<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Remove $block */

$item = $block->getItem();
$product = $item->getProduct();

?>


<?php if ($product->isSaleable()): ?>
    <div class="">
        <div class="actions-primary">
            <button type="button" data-role="tocart" data-post='<?= /* @noEscape */ $block->getItemAddToCartParams($item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>" class="action  primary">
                <i class="fa fa-cart-arrow-down"></i> <span>  <?= $block->escapeHtml(__('Move to Basket')) ?></span>
            </button>
        </div>
    </div>
    <?php else: ?>
        <?php if ($product->getIsSalable()): ?>
            <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $block->escapeHtml(__('In stock')) ?></span>
            </p>
        <?php else: ?>
            <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
            </p>
        <?php endif; ?>
    <?php endif; ?>

<a href="#" data-role="remove"  title="<?= $block->escapeHtmlAttr(__('Remove Item')) ?>" class="btn-remove action delete" data-post='<?= /* @noEscape */ $block->getItemRemoveParams($block->getItem()) ?>'>
    <i class="fa fa-times"></i> <span><?= $block->escapeHtml(__('Remove item')) ?></span>
</a>

