<?php
/**
 * Created by PhpStorm.
 * User: nghiata
 * Date: 21/04/2018
 * Time: 18:34
 */

namespace Yosto\OpcSuccess\Block;


use Magento\Framework\Registry;
use Magento\Framework\View\Element\Template;

class SuccessPage extends \Magento\Framework\View\Element\Template
{
    protected $_coreRegistry;
    public function __construct(
        Registry $registry,
        Template\Context $context,
        array $data = []
    ) {
        $this->_coreRegistry = $registry;
        parent::__construct($context, $data);
    }

    protected function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Order # %1', $this->getOrder()->getRealOrderId()));
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    /**
     * Retrieve current order model instance
     *
     * @return \Magento\Sales\Model\Order
     */
    public function getOrder()
    {
        return $this->_coreRegistry->registry('current_order');
    }
}