<?php
/**
 * Copyright (c) 2018 MageWorkshop. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \MageWorkshop\ImageLoader\Block\Review\ImageUploader $block */
?>
<script type="text/x-magento-init">
{
    "#review-form": {
        "mageWorkshop_imageLoader_reviewFormImageValidation": {
            "maxSize": "<?php /* @escapeNotVerified */ echo $block->getImageLoaderHelper()->getImageSize(); ?>",
            "extensions": <?php /* @escapeNotVerified */echo json_encode($block->getImageLoaderHelper()->getImageTypes()); ?>
        }
    }
}
</script>