<div id="delivery-date">
    <strong><?php echo __('Delivery Date') ?>:</strong>
    <span class="price"><?=$block->getDeliveryDate() ?></span>
</div>
<div id="delivery-comment">
    <strong><?php echo __('Comment') ?>:</strong>
    <br/>
    <span class="price"><?=$block->getDeliveryComment() ?></span>
</div>
<script type="text/javascript">
    require(['jquery'], function($) {
            var boxOrderShipping = $('.order-shipping-method');
            var dateElm = $('#delivery-date').detach();
            boxOrderShipping.append(dateElm);
            var commentElm = $('#delivery-comment').detach();
            boxOrderShipping.append(commentElm);
        }
    );
</script>