<?php /** @var \MageWorkshop\DetailedReview\Block\Review\Product\View\Filters\Date $block */ ?>
<label for="review-filter-by-date" class="filter-label-icon">
    <?php /* @escapeNotVerified */ echo __('Filter by:') ?>
</label>
<select id="review-filter-by-date" class="review-filter-by-date" name="<?php echo $block->getFilterByDateParamName(); ?>">
    <?php foreach ($block->getDateFilterOptions() as $value => $label) : ?>
        <option value="<?php /* @escapeNotVerified */ echo $value; ?>"
            <?php if ($block->isSelected($value)) : ?>selected="selected"<?php endif; ?>
        >
            <?php /* @escapeNotVerified */ echo __($label); ?>
        </option>
    <?php endforeach; ?>
</select>