<?php /** @var \MageWorkshop\DetailedReview\Block\Review\Product\View\Filters\Form $block */ ?>
<form id="review-search-form"
      action="<?php /* @escapeNotVerified */ echo $block->getReviewsApiUrl(); ?>"
      method="get"
      data-mage-init='{"mageWorkshop_detailedReview_reviewFilters": {
          "filterByDate": "#review-filter-by-date",
          "sortDirection": "#review-sort-direction",
          "search": "#review-search-input",
          "clearAllFilters": ".clear-review-filters a"
      }}'
>
    <div id="review-filters" class="filters">
        <?php echo $block->getChildHtml('review.filter.by.date') ?>
    </div>
    <div id="review-sorts" class="filters" data-role="review-sort">
        <?php echo $block->getChildHtml('review.sort.direction') ?>
    </div>
    <div id="review-search" class="filters" data-role="review-search">
        <button type="submit" title="<?= __('Search'); ?>" class="action search submit primary">
            <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
        </button>
        <input id="review-search-input"
               class="search-icon custom-validate-length minimum-length-3"
               name="<?php echo $block->getSearchParamName(); ?>"
               type="text"
               value=""
               placeholder="<?php /* @escapeNotVerified */ echo __('search in reviews'); ?>"
               autocomplete="off"
        />
    </div>
    <div class="clear-review-filters">
        <a href="javascript:void(0);" rel="nofollow">
            <?php /* @escapeNotVerified */ echo __('Clear all filters'); ?>
        </a>
    </div>
</form>