<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>

<li class="authorization-link switcher <?php echo $block->isLoggedIn() ? 'log-out' : 'log-in' ?>" id="authorization-top-link"> <?php /* data-label="<?php echo $block->escapeHtml(__('or')); ?>" */ ?>
	<?php /*?><a <?php /* @escapeNotVerified * / echo $block->getLinkAttributes(); ?><?php /* @escapeNotVerified * / echo $dataPostParam; ?>>
        <?php echo $block->escapeHtml($block->getLabel()); ?>
    </a><?php */?>
	<a style="display:none" class="log-in link" <?php /* @escapeNotVerified */ echo $block->getLinkAttributes(); ?><?php /* @escapeNotVerified */ echo $dataPostParam; ?>>
        <?php echo $block->escapeHtml($block->getLabel()); ?>
    </a>
	<div class="actions dropdown options switcher-options">
		<div class="action toggle switcher-trigger" id="authorization-trigger">
		<i class="fa fa-user"></i>
		</div>

	<?php if( $block->isLoggedIn() ): ?>
		  <div style="display:none;" id="cdz-login-form-dropdown" class="cdz-login-form-dropdown dropdown switcher-dropdown"  data-mage-init='{"dropdownDialog":{
					"appendTo":"#authorization-top-link > .options",
					"triggerTarget":"#authorization-trigger",
					"closeOnMouseLeave": false,
					"triggerClass":"active",
					"parentClass":"active",
					"buttons":null}}'>
                    
                    <?php 
                    $om = \Magento\Framework\App\ObjectManager::getInstance();
                    $customerSession = $om->get('Magento\Customer\Model\Session');
                    
                    ?>
                     
					<a class="link login">Hi, <?= $customerSession->getCustomer()->getName(); ?></a>
					<a href="<?php echo $block->getUrl('').'customer/account/'; ?>" class="link login" id="login_link">My Account</a>
					<a href="<?php echo $block->getUrl('').'sales/order/history/'; ?>" class="link login">My Orders</a>
					<a href="<?php echo $block->getUrl('').'contacts/'; ?>" class="link login">Help</a>
					<a href="<?php echo $block->getUrl('').'customer/account/logout'; ?>" class="link login">Sign Out</a>
			<?php //echo $block->getChildHtml('customer_form_login_mini') ?>
		</div>
	<?php else: ?>
		<div style="display:none;" id="cdz-login-form-dropdown" class="cdz-login-form-dropdown dropdown switcher-dropdown"  data-mage-init='{"dropdownDialog":{
					"appendTo":"#authorization-top-link > .options",
					"triggerTarget":"#authorization-trigger",
					"closeOnMouseLeave": false,
					"triggerClass":"active",
					"parentClass":"active",
					"buttons":null}}'>
					<a href="<?php echo $block->getUrl('customer/account/login'); ?>" class="link login" id="login_link">Login</a>
					<span class="border"></span>
					<a href="<?php echo $block->getUrl('customer/account/create'); ?>" class="link register">Register</a>
			<?php //echo $block->getChildHtml('customer_form_login_mini') ?>
		</div>
	</div>
	<?php endif ?>
</li>

<script>// <![CDATA[
	require([
			'jquery',
			'domReady!'
		], function ($) {
			
				$('#authorization-trigger').on('click', function(e) {
				var linkLocation = $("#login_link").attr("href");
					window.location.href = linkLocation; 
										
				});
				
				
			
		});
	// ]]>
</script>
