<?php
/**
 * Copyright (c) 2018 MageWorkshop. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace MageWorkshop\CustomerPermissions\Model\Rewrite\Customer\Model\Indexer;

class Source extends \Magento\Customer\Model\Indexer\Source
{
    /**
     * Add this missed method for fixing indexing if customer EAV attributes are present
     * in our case it's 'banned_till' attribute
     * Need to be removed as soon as the fix https://github.com/magento/magento2/pull/12729/files is merged
     * Please refer to https://github.com/magento/magento2/issues/10838
     *
     * @param string $fieldName
     * @param mixed $alias
     * @return $this
     */
    public function addAttributeToSelect($fieldName, $alias = null)
    {
        return $this->addFieldToSelect($fieldName, $alias);
    }
}
