<?php
/**
 * Copyright (c) 2018 MageWorkshop. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Review\Block\Form
 */
?>
<?php $url = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>
<div class="block review-add">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Write Your Own Review') ?></strong></div>
    <div class="block-content">
        <?php if ($block->getAllowWriteReviewFlag()): ?>
        <form action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>"
            class="review-form"
            method="post"
            id="review-form"
            data-role="product-review-form"
            data-bind="scope: 'review-form'"
            enctype="multipart/form-data"
        >
            <?php echo $block->getBlockHtml('formkey'); ?>
            <?php echo $block->getChildHtml('form_fields_before')?>
            <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
                <h2 class="tell-us"><?php /* @escapeNotVerified */ echo __('Tell us what you think about this item:'); ?></h2>
                <legend class="legend review-legend"><span><?php /* @escapeNotVerified */ echo __("You're reviewing:"); ?></span><strong><?php echo $block->escapeHtml($block->getProductInfo()->getName()) ?></strong></legend><br />
                <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                    <span id="input-message-box"></span>
                    <fieldset class="field required review-field-ratings">
                        <legend class="label">
                            <span><?php /* @escapeNotVerified */ echo __('Overall Rating') ?><span>
                        </legend>
                        <br/>
                        <p><?php /* @escapeNotVerified */ echo __('Select the number of stars that reflect your overall item rating'); ?></p>
                        <div class="control">
                            <div class="nested" id="product-review-table">
                                <?php foreach ($block->getRatings() as $_rating): ?>
                                    <div class="field choice review-field-rating">
                                        <label class="label" id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                                        <div class="control review-control-vote">
                                        <?php $options = $_rating->getOptions();?>
                                        <?php $iterator = 1; foreach ($options as $_option): ?>
                                            <input
                                                type="radio"
                                                name="ratings[<?php /* @escapeNotVerified */ echo $_rating->getId() ?>]"
                                                id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                                value="<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                                                class="radio"
                                                data-validate="{required:true, messages:{required:'<?= __('Please select one of each of the ratings above.'); ?>'}}"
                                                aria-labelledby="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label" />
                                            <label
                                                class="rating-<?php /* @escapeNotVerified */ echo $iterator; ?>"
                                                for="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                                title="<?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?>"
                                                id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label">
                                                <span><?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?></span>
                                            </label>
                                        <?php $iterator++; ?>
                                        <?php endforeach; ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                        </div>
                    </fieldset>
                <?php endif ?>
                <p class="your-review"><?php /* @escapeNotVerified */ echo __('Your Review'); ?></p>
                <p><?php /* @escapeNotVerified */ echo __('Share your opinion with others by writing a detailed review'); ?></p>
                <?php echo $block->getChildHtml('review.form.fields.wrapper'); ?>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="actions-toolbar review-form-actions">
                    <div class="primary actions-primary">
                        <button class="button-back"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></button>
                        <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit Review') ?></span></button>
                    </div>
                </div>
            </fieldset>
        </form>
        <script type="text/x-magento-init">
        {
            "[data-role=product-review-form]": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            },
            "#review-form": {
                "mageWorkshop_detailedReview_reviewCustomValidateLength": {},
                "MageWorkshop_DetailedReview/js/error-placement": {},
                "mageWorkshop_detailedReview_reviewForm": {
                    "productUrl": <?php /* @escapeNotVerified */ echo json_encode($url); ?>
                },
                "Magento_Captcha/captcha": {
                    "url": "<?php /* @escapeNotVerified */ echo $block->getUrl('captcha/refresh/'); ?>"
                }
            }
        }
        </script>
        <script>
            // @TODO: Used for swatches. Need to move this to plugin
            require(["jquery", "jquery/ui"], function ($) {
                $('body').on('click', '.mageworkshop-option-item', function () {
                    var parent = $(this).parents('.field-block');
                    parent.find('.mageworkshop-option-item').removeClass('selected');
                    parent.find('input').val($(this).attr('data-value'));
                    $(this).addClass('selected');
                });
            });
        </script>
        <?php else: ?>
            <div class="message info notlogged" id="review-form">
                <div>
                    <?php /* @escapeNotVerified */ echo __('Only registered users can write reviews. Please, <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()) ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
